// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// predict_onehot_dense
NumericMatrix predict_onehot_dense(List onehot, DataFrame df);
RcppExport SEXP onehot_predict_onehot_dense(SEXP onehotSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type onehot(onehotSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_onehot_dense(onehot, df));
    return rcpp_result_gen;
END_RCPP
}
// predict_onehot_sparse
List predict_onehot_sparse(List onehot, DataFrame df);
RcppExport SEXP onehot_predict_onehot_sparse(SEXP onehotSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type onehot(onehotSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_onehot_sparse(onehot, df));
    return rcpp_result_gen;
END_RCPP
}
