# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_onehot_dense <- function(onehot, df) {
    .Call('onehot_predict_onehot_dense', PACKAGE = 'onehot', onehot, df)
}

predict_onehot_libsvm <- function(onehot, df, y, outfile) {
    .Call('onehot_predict_onehot_libsvm', PACKAGE = 'onehot', onehot, df, y, outfile)
}

predict_onehot_sparse <- function(onehot, df) {
    .Call('onehot_predict_onehot_sparse', PACKAGE = 'onehot', onehot, df)
}

